### ISSUE TITLE
Implement command to edit remark

### ISSUE THREAD

**Issue by YangYafei1998** [CS2103-AY1819S1-T10-2/main#12]
**Description:** Edits the remark for a person specified in the INDEX.
**Command Word:** COMMAND_WORD = remark
**Format:** COMMAND_WORD INDEX r/REMARK
**Examples:**
- remark 1 r/Likes to drink coffee.
Edits the remark for the first person to likes to drink coffee.
- remark 1 r/
Removes the remark for the first person.

**Comment by giamjuxian** [comment]
Completed
