### ISSUE TITLE
Implement command to add and delete medical history

### ISSUE THREAD

**Issue by YangYafei1998** [CS2103-AY1819S1-T10-2/main#13]
**Description:** Add/Delete medical history of a patient specified by the INDEX
**Command Word:** 
- COMMAND_WORD = add-medical-history
- COMMAND_WORD = delete-medical-history

**Format:** COMMAND_WORD INDEX c/CONDITION a/ALLERGY

**Comment by giamjuxian** [comment]
Completed. Good job!
