### ISSUE TITLE
Format the command informations

### ISSUE THREAD

**Issue by giamjuxian** [CS2103-AY1819S1-T10-2/main#132]
**Example:** 
Invalid command format! 
add-prescription: Adds a prescription to an appointment. Parameters: APPOINTMENT_ID pn/MEDICINE_NAME pd/DOSAGE pc/CONSUMPTION_PER_DAY 
Example: add-prescription 10005 pn/Paracetamol pd/2 pc/3 

SHOULD BE

Invalid command format! 
add-prescription: Adds a prescription to an appointment. 
Parameters: APPOINTMENT_ID pn/MEDICINE_NAME pd/DOSAGE pc/CONSUMPTION_PER_DAY 
Example: add-prescription 10005 pn/Paracetamol pd/2 pc/3

**Comment by florafong97** [comment]
Checked through all commands, should be all the same format now
