### ISSUE TITLE
Adding prescription to completed appointment does not show up in UI

### ISSUE THREAD

**Issue by giamjuxian** [CS2103-AY1819S1-T10-2/main#133]
![image](https://user-images.githubusercontent.com/26025570/48299871-5f8a4480-e50e-11e8-9f9f-8291eebf324f.png)
Adding chocolate to prescription.

![image](https://user-images.githubusercontent.com/26025570/48299874-6c0e9d00-e50e-11e8-9872-fa217f26b990.png)
No Chocolate

Does not add into xml file as well. Seems to appear when you have duplicate patients with same name different number. Adding prescription to first patient's appointment then second patient's appointment result in the second prescription to not be added to the patient

Under storage, it adds to the appointment itself but not the doctor and patient.

**Comment by florafong97** [comment]
if got duplicate contact, does not add to the second one

**Comment by florafong97** [comment]
need to check for both name and phone number
