### ISSUE TITLE
Test cases for Prescription commands

### ISSUE THREAD

**Issue by giamjuxian** [CS2103-AY1819S1-T10-2/main#46]
Include test cases for prescription commands to ensure that there is no bug in this feature. Make the whole HealthBook more robust.

**Description**: Include test cases for prescription commands
**Command** **Word**: add-prescription, delete-prescription

**Comment by florafong97** [comment]
included cases for:
- invalid ID
- duplicate prescription
- prescription does not exist
- able to be used on completed and ongoing appointments
