### ISSUE TITLE
add-appointment exceptions

### ISSUE THREAD

**Issue by florafong97** [CS2103-AY1819S1-T10-2/main#61]
include cases for: 
doctor already have appt at that time
patient already have appt at that time
set a time period for each appt (maybe 15 mins), doesn't make sense to be able to set an appt at 15:00 and another at 15:01 to the same doctor

optional things:
how to set a opening/closing time for clinic -> unless open 24/7
what if doctor is not free at certain periods ie lunch/ on vacation/ off day

+other cases we can think of

**Comment by giamjuxian** [comment]
Resolved. Test cases will be added #75
